const express = require('express')
const router = express.Router()
const userRouter = require('./users')
const categoryRouter = require('./categories')
const dressRouter = require('./dress')
const favoriteRouter = require('./favorite')
const storeRouter = require('./store')
const { authentication } = require('../middlewares/authentication')
const paymentRouter = require('./payment')
router.use(userRouter)
router.use(categoryRouter)
router.use(storeRouter)
router.use(dressRouter)
router.use(authentication)
router.use(favoriteRouter)
router.use(paymentRouter)
module.exports = router